version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
      
  buyer_svc:
    image: 'mainakdalui/buyer-svc-imgdock:v1'
    container_name: buyer-svc-condock
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - zookeeper
      - kafka
      - redis
      
  seller_svc:
    image: 'mainakdalui/seller-svc-imgdock:v1'
    container_name: seller-svc-condock
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - zookeeper
      - kafka
      - redis